### ISSUE TITLE
Provider error return

### ISSUE THREAD

**Issue by tltary** [wavesplatform/signer#1]
I noticed that provider errors are returned by text not by the object, for example as invoke transaction error

When the text returning, I can’t find out what exactly happened, because there is no error code

It would be nice to typify the error output by the provider side also returns as object

As an example
```js
{
 error: errorCode,
 message: errorMessage
}
```

**Comment by tsigel** [comment]
Thanks for your feedback!

This library only returns errors that were received in the provider. Return of error codes is already in the list of providers' improvements.

Thanks again for your feedback!
