### ISSUE TITLE
Suggestion for user experience

### ISSUE THREAD

**Issue by christopheSeeka** [wavesplatform/signer#10]
First of all sorry to post here, i think this is more for waves.exchange provider but i cant post on the gitlab.

Could we consider something like a direct link in waves.exchange to the export of account as json or so ? 

Like waves.exchange/export/{address} for example ? because with Waves Signer, currently when integrated in 3rd party app, if the user have no account yet, he set a password and automatically get an account/address, which is very cool but then he dont have his recovery seed, he may buy services then later clear browser data storage and lose everything. 

It would really ease UX to have a simple way or direct link for him to go get seed/ json export. At the moment in my app i tell users to go get it on waves.echange but once they are there most will just be lost if first time on dex (needs go upper right, setting, security, click export json etc).

I think this would make the whole thing even better. 

Sorry again if not proper place for suggestion.

**Comment by tsigel** [comment]
Hello! 
Thanks for your feedback!

We will try to transfer your request to the development team of the wave.exchange provider.

Cheers!
