### ISSUE TITLE
Failing without error message when opening in browser with third party cookies disabled

### ISSUE THREAD

**Issue by WavescapTorben** [wavesplatform/signer#13]
Failing without error message when opening in browser with third party cookies disabled.

Maybe it would be even nicer when signer would provide a way to create a address and store its seed in localStorage of the current domain?

**Comment by tsigel** [comment]
Hello! Thanks for your feedback!

> Failing without error message when opening in browser with third party cookies disabled.

Are you talking about `@waves.exchange/provider-web`?

> Maybe it would be even nicer when signer would provide a way to create a address and store its seed in localStorage of the current domain?

If we talk about the package `@waves.exchange/provider-web`:
The main idea of the library is that third-party sites do not have access to user seed phrase.

If we talk about the package `@waves/signer`:
You can use any provider, including one that allows you to store user seed on your site.

**Comment by WavescapTorben** [comment]
Yes I am talking about provider-web. Where is best place for telling them?

> You can use any provider, including one that allows you to store user seed on your site.

Ah yes cool)

Thanks for your great tool!

**Comment by tsigel** [comment]
> Yes I am talking about provider-web. Where is best place for telling them?

[Here](https://github.com/waves-exchange/provider-web).

Cheers!
