### ISSUE TITLE
[FEATURE] QR-code

### ISSUE THREAD

**Issue by WavescapTorben** [wavesplatform/signer#14]
Would love to have a button for seeing a QR-code of my address for quickly charge it with my phone.

**Comment by tsigel** [comment]
Thanks for your feedback!

This feature for `@waves.exchange/provider-web`?

**Comment by WavescapTorben** [comment]
Ah yes I think so.

**Comment by tsigel** [comment]
Thanks!
Can your following functions for `@waves.exchange/provider-web` create [their](https://github.com/waves-exchange/provider-web) repositories?
We will pass on your idea to the wave sharing team.
