### ISSUE TITLE
[Question] Automatic signin

### ISSUE THREAD

**Issue by christopheSeeka** [wavesplatform/signer#20]
Some users are asking me if we have an option to keep account logged in on refresh with automatic signin autorisation for a certain time like what we have in Waves Keeper. Would this be something possible to integrate on signer too ?

**Comment by tsigel** [comment]
Hello!
Are your talking about [provider-web](https://github.com/waves-exchange/provider-web)?

**Comment by christopheSeeka** [comment]
Ok might be on provider-web side yes, will post there then thanks :)
