### ISSUE TITLE
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@waves%2fwaves-js - Not found

### ISSUE THREAD

**Issue by zababurinsv** [wavesplatform/signer#3]
I get project clone  https://github.com/wavesplatform/signer/issues/new

trying use npm install and getting this error

npm WARN deprecated @types/dotenv@8.2.0: This is a stub types definition. dotenv provides its own type definitions, so you do not need this installed.
npm WARN deprecated @types/bignumber.js@5.0.0: This is a stub types definition for bignumber.js (https://github.com/MikeMcl/bignumber.js/). bignumber.js provides its own type definitions, so you don't need @types/bignumber.js installed!
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@waves%2fwaves-js - Not found
npm ERR! 404 
npm ERR! 404  '@waves/waves-js@0.0.16' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of '@waves/seed-provider'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sergey/.npm/_logs/2020-01-04T08_37_50_379Z-debug.log

what is the  https://registry.npmjs.org/@waves%2fwaves-js  ?

**Comment by tsigel** [comment]
Hello! We rename repo before publish. Try to git pull and npm install again.

**Comment by dalu547** [comment]
When iam trying to install plugin through npm , i am getting below error.
**D:\Data\WorkSpace\Ionic\MathApp\mathApp>npm install cordova-plugin-mathcal**
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/cordova-plugin-mathcal - Not found
npm ERR! 404
npm ERR! 404  'cordova-plugin-mathcal@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dalayya.kalla\AppData\Roaming\npm-cache\_logs\2020-02-12T08_01_24_803Z-debug.log
**Did i miss any?**
