### ISSUE TITLE
Mass transfer give a Error: Unsupported type!

### ISSUE THREAD

**Issue by christopheSeeka** [wavesplatform/signer#4]
When i try a basic massTransfer i always get the following error:

Error: Unsupported type!

Here basic example giving the error:

`document.querySelector(".js-mass-transfer").addEventListener("click", async function() {
  const data = {
    transfers: [
      {
        amount: 1,
        recipient: "3MvujUZTtoANRzrKYKzx99Vtb9TUh6VPCDm"
      },
      {
        amount: 2,
        recipient: "3NB38F1wMpKsVQsXVPm28G2X6rViRbZwpjC"
      }
    ]
  };
const massTx = await signer.massTransfer(data).broadcast();
});`

**Comment by tsigel** [comment]
Hello! 

This error in @waves.exchange/provider-web. 
Now this provider support only transfer, data and invoke transactions.
Your can create issue or PR [here](https://gitlab.waves.exchange/we-public/provider-web).
