### ISSUE TITLE
When custom feeAssetId with no payment, window show "undefined"

### ISSUE THREAD

**Issue by christopheSeeka** [wavesplatform/signer#5]
When i have an invoke transaction without a payment and using feeAssetId parameter, the window show "undefined" aside of the transaction fee amount in custom token. Transaction still work.

See attached image.

Also would be usefull to be able to see the data that will be written in the confirmation window like it was in Keeper, currently we cannot expand when click on "call function" to see the detail.

![feeAssetId](https://user-images.githubusercontent.com/50763365/71798130-e80d6200-308b-11ea-90b9-0f49b286628d.jpg)

**Comment by tsigel** [comment]
Hello! Thanks for your feedback!

> When i have an invoke transaction without a payment and using feeAssetId parameter, the window show "undefined" aside of the transaction fee amount in custom token. Transaction still work.

This problem in @waves.exchange/provider-web. I clone your [issue](https://gitlab.waves.exchange/we-public/provider-web/issues/1) in that repo.

> Also would be usefull to be able to see the data that will be written in the confirmation window like it was in Keeper, currently we cannot expand when click on "call function" to see the detail.

In this repo, we only create a protocol for communication with providers. All UI solutions are developed on the side of providers. We will pass on your comments to the developers.

Cheers!

**Comment by christopheSeeka** [comment]
Got it thank you :)
