### ISSUE TITLE
There is no a simple up to date working example

### ISSUE THREAD

**Issue by deemru** [wavesplatform/signer#53]
As of 30.04.2021, i didn`t find a simple working example to copy-paste and adopt from.

You provide a single example at https://github.com/vlzhr/crypto-donate (https://vlzhr.github.io/crypto-donate/) but it does not work: https://github.com/vlzhr/crypto-donate/issues/2

It is a sad picture actually.

**Comment by joaobalzer** [comment]
I agreed i start a project with nft generation and NOTHING is working

**Comment by joaobalzer** [comment]
The only place in the web that i found with working code was Waves Africa

**Comment by tsigel** [comment]
https://github.com/tsigel/crypto-donate - this is worked

**Comment by joaobalzer** [comment]
Thanks
