### ISSUE TITLE
Switching between accounts

### ISSUE THREAD

**Issue by christopheSeeka** [wavesplatform/signer#6]
What is the best option to implement a switch account button ?

If i just call signer.login() again while logged in, the popin dont show up or sometimes show up and disappear right away, 
if i call logout() followed by login() right away, its ok but if user cancel the request then he end up logged out.

Thank you in advance

**Comment by tsigel** [comment]
Hello! 

Best way - call logout() and after then call login().
Second call `login()` method just return active user data.

**Comment by christopheSeeka** [comment]
Thank you.
