### ISSUE TITLE
Wrong event format!

### ISSUE THREAD

**Issue by christopheSeeka** [wavesplatform/signer#9]
I keep getting this "Wrong event format!" in browser console, is it a problem in my implementation?

![wrong-event-format](https://user-images.githubusercontent.com/50763365/72323507-e1ae6400-36e3-11ea-9d6f-0d613e832ebd.jpg)

Are all this WindowAdapter log temporary ?

Thank you.

**Comment by tsigel** [comment]
This is not error, its warning. This is debug logs for detect connect problem with provider.

**Comment by christopheSeeka** [comment]
Got it thank you.

**Comment by tsigel** [comment]
We will remove this logs in the next releases.
